---
# yamllint disable rule:line-length
###############################################################################
# Config Service
###############################################################################
# VSFTPd is ideal for configuration encapsulation. It is extremely stable, and
# has very stringent and complex configuration setup. Encapsulation makes sense
# to ensure complex setup requirements are met with minimal user complexity.
# Check path length as config is always run.
#
# If service fails to start with 'status=2/INVALIDARGUMENT' in syslog, manually
# execute the configuration file to determine the exact cause:
#
#   vsftpd /etc/vsftpd.conf
#
# Chroot environments require read-only root directories; otherwise logins
# result in:
#
#   500 OOPS: vsftpd: refusing to run with writable root inside chroot ()
#
# Chroot environments with the service local user must set user home directory
# read-only:
#
#   vsftpd_srv_home_mode: '0550'
#
# Specific container environments will fail to create vsftpd.log file when used
# with hardening. Touch file explicitly to prevent issue from occurring.
#
# Reference:
# * https://wiki.archlinux.org/title/Very_Secure_FTP_Daemon
# * https://security.appspot.com/vsftpd/vsftpd_conf.html
# * https://unix.stackexchange.com/questions/181436/vsftpd-wont-start-systemd1-vsftpd-service-main-process-exited-code-exite
# * https://www.server-world.info/en/note?os=Debian_12&p=ftp&f=1
# yamllint enable rule:line-length

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._secure_d }}'
  when: vsftpd__srv._secure_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ vsftpd___app._secure_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0750'
        state: 'directory'
      loop: '{{ query("community.general.filetree", vsftpd__srv._secure_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ vsftpd___app._secure_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0640'
      loop: '{{ query("community.general.filetree", vsftpd__srv._secure_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ vsftpd___app._secure_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: vsftpd__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ vsftpd__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", vsftpd__srv._secure_d) |
          map(attribute='path') |
          map('regex_replace', '^', vsftpd___app._secure_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._user_d }}'
  when: vsftpd__srv._secure_d | length > 0
  block:
    - name: 'Config | filetree | set managed directories'
      ansible.builtin.file:
        path: '{{ vsftpd___app._user_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0750'
        state: 'directory'
      loop: '{{ query("community.general.filetree", vsftpd__srv._user_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'directory'

    - name: 'Config | filetree | set managed files'
      ansible.builtin.template:
        src: '{{ item.src }}'
        dest: '{{ vsftpd___app._user_d ~ "/" ~ item.path }}'
        owner: 'root'
        group: 'root'
        mode: '0640'
      loop: '{{ query("community.general.filetree", vsftpd__srv._user_d) }}'
      loop_control:
        label: '{{ item.path }}'
      when: item.state == 'file'

    - name: 'Config | filesystem | query remote files'
      ansible.builtin.find:
        paths: '{{ vsftpd___app._user_d }}'
        file_type: 'any'
        hidden: true
        recurse: true
      register: vsftpd__remote

    - name: 'Config | filetree | remove unmanaged files and directories'
      ansible.builtin.file:
        path: '{{ item.path }}'
        state: 'absent'
      loop: '{{ vsftpd__remote.files | sort(attribute="path", reverse=true) }}'
      loop_control:
        label: '{{ item.path }}'
      when: >
        item.path not in
        (
          query("community.general.filetree", vsftpd__srv._user_d) |
          map(attribute='path') |
          map('regex_replace', '^', vsftpd___app._user_d ~ "/") | list
        )

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._cfg }}'
  ansible.builtin.template:
    src: 'vsftpd.conf.j2'
    dest: '{{ vsftpd___app._cfg }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Config | filesystem | touch logs'
  ansible.builtin.file:
    path: '{{ vsftpd__cfg._log }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
    state: 'touch'
  loop:
    - '{{ vsftpd__cfg._log }}'
    - '{{ vsftpd__cfg._xfer_log }}'

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._banner }}'
  when: vsftpd__srv._banner | length > 0
  ansible.builtin.template:
    src: 'vsftpd.d/file.j2'
    dest: '{{ vsftpd___app._banner }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
  vars:
    items: '{{ [vsftpd__srv._banner] }}'

- name: '{{ "Config | filesystem | remove " ~ vsftpd___app._banner }}'
  when: vsftpd__srv._banner | length == 0
  ansible.builtin.file:
    path: '{{ vsftpd___app._banner }}'
    state: 'absent'

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._banned_emails }}'
  when: vsftpd_cfg_deny_email_enable
  ansible.builtin.template:
    src: 'vsftpd.d/file.j2'
    dest: '{{ vsftpd___app._banned_emails }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  vars:
    items: '{{ vsftpd__srv._banned_emails }}'

- name: '{{ "Config | filesystem | remove " ~ vsftpd___app._banned_emails }}'
  when: not vsftpd_cfg_deny_email_enable
  ansible.builtin.file:
    path: '{{ vsftpd___app._banned_emails }}'
    state: 'absent'

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._chroot_list }}'
  when: vsftpd_cfg_chroot_list_enable
  ansible.builtin.template:
    src: 'vsftpd.d/file.j2'
    dest: '{{ vsftpd___app._chroot_list }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  vars:
    items: '{{ vsftpd__srv._chroot_list }}'

- name: '{{ "Config | filesystem | remove " ~ vsftpd___app._chroot_list }}'
  when: not vsftpd_cfg_chroot_list_enable
  ansible.builtin.file:
    path: '{{ vsftpd___app._chroot_list }}'
    state: 'absent'

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._user_list }}'
  when: vsftpd_cfg_userlist_enable
  ansible.builtin.template:
    src: 'vsftpd.d/file.j2'
    dest: '{{ vsftpd___app._user_list }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  vars:
    items: '{{ vsftpd__srv._userlist }}'

- name: '{{ "Config | filesystem | remove " ~ vsftpd___app._user_list }}'
  when: not vsftpd_cfg_userlist_enable
  ansible.builtin.file:
    path: '{{ vsftpd___app._user_list }}'
    state: 'absent'

- name: '{{ "Config | filesystem | set " ~ vsftpd___app._email_passwords }}'
  when: vsftpd_cfg_secure_email_list_enable
  ansible.builtin.template:
    src: 'vsftpd.d/file.j2'
    dest: '{{ vsftpd___app._email_passwords }}'
    owner: 'root'
    group: 'root'
    mode: '0600'
  vars:
    items: '{{ vsftpd__srv._email_passwords }}'

- name: '{{ "Config | filesystem | remove " ~ vsftpd___app._email_passwords }}'
  when: not vsftpd_cfg_secure_email_list_enable
  ansible.builtin.file:
    path: '{{ vsftpd___app._email_passwords }}'
    state: 'absent'

- name: 'Config | filesystem | set local user login root directory'
  when: vsftpd__cfg._local_root | length > 0
  block:
    - name: '{{ "Install | filesystem | set " ~ vsftpd__cfg._local_root }}'
      ansible.builtin.file:
        path: '{{ vsftpd__cfg._local_root }}'
        owner: '{{ vsftpd__srv._local_root_uid }}'
        group: '{{ vsftpd__srv._local_root_gid }}'
        mode: '{{ vsftpd__srv._local_root_mode }}'
        recurse: '{{ vsftpd__srv._local_root_recursive }}'
        state: 'directory'
  rescue:
    - name: '{{ "Install ⛑ | filesystem | set " ~ vsftpd__cfg._local_root }}'
      ansible.builtin.file:
        path: '{{ vsftpd__cfg._local_root }}'
        owner: '{{ vsftpd__srv._local_root_uid }}'
        group: '{{ vsftpd__srv._local_root_gid }}'
        mode: '{{ vsftpd__srv._local_root_mode }}'
        recurse: '{{ vsftpd__srv._local_root_recursive }}'
        state: 'directory'
      become: true
      become_user: '{{ vsftpd__srv._user }}'

- name: 'Config | filesystem | set anon user login root directory'
  when: vsftpd__cfg._anon_root | length > 0
  block:
    - name: '{{ "Install | filesystem | set " ~ vsftpd__cfg._anon_root }}'
      ansible.builtin.file:
        path: '{{ vsftpd__cfg._anon_root }}'
        owner: '{{ vsftpd__srv._anon_root_uid }}'
        group: '{{ vsftpd__srv._anon_root_gid }}'
        mode: '{{ vsftpd__srv._anon_root_mode }}'
        recurse: '{{ vsftpd__srv._anon_root_recursive }}'
        state: 'directory'
  rescue:
    - name: '{{ "Install ⛑ | filesystem | set " ~ vsftpd__cfg._anon_root }}'
      ansible.builtin.file:
        path: '{{ vsftpd__cfg._anon_root }}'
        owner: '{{ vsftpd__srv._anon_root_uid }}'
        group: '{{ vsftpd__srv._anon_root_gid }}'
        mode: '{{ vsftpd__srv._anon_root_mode }}'
        recurse: '{{ vsftpd__srv._anon_root_recursive }}'
        state: 'directory'
      become: true
      become_user: '{{ vsftpd__srv._user }}'
