---
###############################################################################
# Install Packages
###############################################################################

- name: 'Install | packages'
  ansible.builtin.include_role:
    name: 'r_pufky.deb.apt'
  vars:
    apt_packages:
      - '{{ vsftpd_role_packages }}'
      - '{{
          vsftpd_role_virtual_user_packages
          if _vsftpd_srv_virtual_users.raw | length > 0 else
          []
        }}'
    apt_package_update_cache: true

- name: 'Prep | stop services'
  ansible.builtin.systemd:
    name: '{{ item }}'
    state: 'stopped'
  failed_when: false
  loop:
    - 'vsftpd.service'

- name: 'Prep | create service config directory'
  ansible.builtin.file:
    path: '{{ vsftpd_role_service_dir }}'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'
