---
- name: 'Prep'
  ansible.builtin.include_tasks: 'prep.yml'

- name: 'Install'
  when: vsftpd_flg_install
  ansible.builtin.include_tasks: 'install.yml'

- name: 'Config'
  ansible.builtin.include_tasks: 'config.yml'

- name: 'Virtual users'
  ansible.builtin.include_tasks: 'virtual_users.yml'
- name: 'Start'
  ansible.builtin.import_tasks: 'start.yml'
