---
###############################################################################
# Manager Roundcube Users
###############################################################################
# Check if user exists and create if enabled.
#
# Args:
#   vsftpd_user: string vsftpd username.
#   vsftpd_group: string vsftpd group.
#   vsftpd_create_user: boolean true to create role default user.
#   vsftpd_default_user: dict containing builitin.user options for vsftpd.
#   vsftpd_default_group: dict containing builitin.group options for vsftpd.

- name: 'manage users | confirm user exists'
  ansible.builtin.command: 'id {{ vsftpd_user }}'
  register: _vsftpd_user_exists
  changed_when: _vsftpd_user_exists.rc > 0
  failed_when: false

- name: 'manage users | confirm group exists'
  ansible.builtin.command: 'groups {{ vsftpd_group }}'
  register: _vsftpd_group_exists
  changed_when: _vsftpd_group_exists.rc > 0
  failed_when: false

- name: 'manage users | create vsftpd group'
  ansible.builtin.group:
    name:  '{{ vsftpd_default_group.name }}'
    gid:   '{{ vsftpd_default_group.gid }}'
    state: 'present'
  when: vsftpd_create_user and _vsftpd_group_exists.rc != 0

- name: 'manage users | create vsftpd user (logins disabled)'
  ansible.builtin.user:
    name:            '{{ vsftpd_default_user.name }}'
    group:           '{{ vsftpd_default_user.group }}'
    uid:             '{{ vsftpd_default_user.uid }}'
    shell:           '{{ vsftpd_default_user.shell }}'
    home:            '{{ vsftpd_default_user.home }}'
    comment:         '{{ vsftpd_default_user.comment }}'
    create_home:     '{{ vsftpd_default_user.create_home }}'
    password:        '{{ vsftpd_default_user.password }}'
    password_lock:   '{{ vsftpd_default_user.password_lock }}'
    update_password: '{{ vsftpd_default_user.update_password }}'
    expires:         '{{ vsftpd_default_user.expires }}'
    system:          '{{ vsftpd_default_user.system }}'
    state:           'present'
  when: vsftpd_create_user and _vsftpd_user_exists.rc != 0
