---
###############################################################################
# Prep
###############################################################################
# Create user and set home directory if needed and determine UID/GID for
# potential remote filesystems. Stop services if they exist.
#
# Reference:
# * https://wiki.archlinux.org/title/Very_Secure_FTP_Daemon
# * https://security.appspot.com/vsftpd.html

- name: 'Prep | assert mutually exclusive listen options'
  when: _vsftpd_cfg_listen.raw or _vsftpd_cfg_listen_ipv6.raw
  ansible.builtin.assert:
    quiet: true
    that: _vsftpd_cfg_listen.raw != _vsftpd_cfg_listen_ipv6.raw
    fail_msg: |
      ✘ vsftpd_cfg_listen, vsftpd_cfg_listen_ipv6 are mutually exclusive.

           vsftpd_cfg_listen: {{ _vsftpd_cfg_listen.raw }}
      vsftpd_cfg_listen_ipv6: {{ _vsftpd_cfg_listen_ipv6.raw }}

- name: 'Prep | manage users'
  when: _vsftpd_srv_create_user.raw
  ansible.builtin.include_role:
    name: 'r_pufky.deb.users'
    tasks_from: 'role_account_add.yml'
  vars:
    users_role_user: '{{ vsftpd_role_user }}'
    users_role_group: '{{ vsftpd_role_group }}'

- name: 'Prep | enumerate system user {{ _vsftpd_srv_user.raw }}'
  ansible.builtin.user:
    name: '{{ _vsftpd_srv_user.raw }}'
    state: 'present'
  check_mode: true
  changed_when: false
  register: _vsftpd_srv_user_query

- name: 'Prep | parse system user UID/GID'
  ansible.builtin.set_fact:
    _vsftpd_srv_user: '{{
        _vsftpd_srv_user |
        combine({"role_uid": _vsftpd_srv_user_query.uid,
                 "role_home": _vsftpd_srv_user_query.home})
      }}'
    _vsftpd_srv_group: '{{
        _vsftpd_srv_group |
        combine({"role_gid": _vsftpd_srv_user_query.group})
      }}'

- name: 'Prep | set user home directory'
  ansible.builtin.file:
    path: '{{ _vsftpd_srv_user.role_home }}'
    owner: '{{ _vsftpd_srv_user.role_uid }}'
    group: '{{ _vsftpd_srv_group.role_gid }}'
    mode: '{{ _vsftpd_srv_user_home_mode.raw }}'
    state: 'directory'
  become: true
  become_user: '{{
      _vsftpd_srv_user.raw
      if _vsftpd_srv_user_data_manage_enable.raw else
      "root"
    }}'

- name:
    'Prep | enumerate local root user {{ _vsftpd_srv_local_root_user.raw }}'
  ansible.builtin.user:
    name: '{{ _vsftpd_srv_local_root_user.raw }}'
    state: 'present'
  check_mode: true
  changed_when: false
  register: _vsftpd_srv_user_local_root_query

- name: >
    Prep | enumerate local root group
    {{ _vsftpd_srv_local_root_group.raw }}
  ansible.builtin.group:
    name: '{{ _vsftpd_srv_local_root_group.raw }}'
    state: 'present'
  check_mode: true
  changed_when: false
  register: _vsftpd_srv_user_local_group_query

- name: 'Prep | parse local root UID/GID'
  ansible.builtin.set_fact:
    _vsftpd_srv_local_root_user: '{{
        _vsftpd_srv_local_root_user |
        combine({"role_uid": _vsftpd_srv_user_local_root_query.uid})
      }}'
    _vsftpd_srv_local_root_group: '{{
        _vsftpd_srv_local_root_group |
        combine({"role_gid": _vsftpd_srv_user_local_group_query.gid})
      }}'

- name:
    'Prep | enumerate anon root user {{ _vsftpd_srv_anon_root_user.raw }}'
  ansible.builtin.user:
    name: '{{ _vsftpd_srv_anon_root_user.raw }}'
    state: 'present'
  check_mode: true
  changed_when: false
  register: _vsftpd_srv_user_anon_root_query

- name: >
    Prep | enumerate anon root group
    {{ _vsftpd_srv_anon_root_group.raw }}
  ansible.builtin.group:
    name: '{{ _vsftpd_srv_anon_root_group.raw }}'
    state: 'present'
  check_mode: true
  changed_when: false
  register: _vsftpd_srv_user_anon_group_query

- name: 'Prep | parse local root UID/GID'
  ansible.builtin.set_fact:
    _vsftpd_srv_anon_root_user: '{{
        _vsftpd_srv_anon_root_user |
        combine({"role_uid": _vsftpd_srv_user_anon_root_query.uid})
      }}'
    _vsftpd_srv_anon_root_group: '{{
        _vsftpd_srv_anon_root_group |
        combine({"role_gid": _vsftpd_srv_user_anon_group_query.gid})
      }}'
