---
# yamllint disable rule:line-length
###############################################################################
# Manager Virtual Users
###############################################################################
# Create virtual users.
#
# Reference:
# * https://wiki.archlinux.org/title/Very_Secure_FTP_Daemon
# * https://www.howtoforge.com/how-to-install-vsftpd-ftp-server-on-debian-11/
# * https://askubuntu.com/questions/575523/how-to-setup-virtual-users-for-vsftpd-with-access-to-a-specific-sub-directory
# * https://linuxconfig.org/how-to-setup-vsftpd-on-debian
# yamllint enable rule:line-length

- name: 'Virtual users | enable'
  when: _vsftpd_srv_virtual_users.raw | length > 0
  block:
    - name: 'Virtual users | enable | clear virtual users'
      ansible.builtin.file:
        path: '{{ _vsftpd_srv_virtual_users.role_dest }}'
        state: 'absent'

    - name: 'Virtual users | enable | add virtual users'
      community.general.htpasswd:
        path: '{{ _vsftpd_srv_virtual_users.role_dest }}'
        name: '{{ item.user }}'
        password: '{{ item.pass }}'
        crypt_scheme: 'md5_crypt'
        owner: 'root'
        group: 'root'
        mode: '0640'
        state: 'present'
      loop: '{{ _vsftpd_srv_virtual_users.raw }}'
      loop_control:
        label: '{{ item.user }}'

    - name: 'Virtual users | enable | add PAM vsftpd_virtual module'
      ansible.builtin.template:
        src: 'vsftpd_virtual.j2'
        dest: '{{ _vsftpd_cfg_pam_service_name.role_dest }}'
        owner: 'root'
        group: 'root'
        mode: '0644'

- name: 'Virtual users | disable'
  when: _vsftpd_srv_virtual_users.raw | length == 0
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '{{ _vsftpd_srv_virtual_users.role_dest }}'
    - '{{ _vsftpd_cfg_pam_service_name.role_dest }}'
