---
###############################################################################
# Manager vsftpd Virtual Users
###############################################################################
# Create virtual users.
#
#
#vsftpd_virtual_users
# Reference:
# * https://www.howtoforge.com/how-to-install-vsftpd-ftp-server-on-debian-11/
# * https://askubuntu.com/questions/575523/how-to-setup-virtual-users-for-vsftpd-with-access-to-a-specific-sub-directory
# * https://linuxconfig.org/how-to-setup-vsftpd-on-debian

- name: 'virtual | enabling virtual users'
  block:
    - name: 'virtual | clear virtual users'
      ansible.builtin.file:
        path:  '{{ vsftpd_default_virtual_users_file }}'
        state: 'absent'
      failed_when: false
      changed_when: false

    - name: 'virtual | add virtual users'
      community.general.htpasswd:
        path:     '{{ vsftpd_default_virtual_users_file }}'
        name:     '{{ item.user }}'
        password: '{{ item.pass }}'
        crypt_scheme: 'md5_crypt'
        owner: 'root'
        group: 'root'
        mode:  0640
        state: 'present'
      loop: '{{ vsftpd_virtual_users }}'
      no_log: true # passwords

    - name: 'virtual | add vsftpd virtual pam module'
      ansible.builtin.template:
        src:   'vsftpd_virtual.j2'
        dest:  '{{ vsftpd_default_virtual_users_pam_file }}'
        owner: 'root'
        group: 'root'
        mode:  0640
  when: vsftpd_virtual_users|length > 0

- name: 'virtual | disabling virtual users'
  block:
    - name: 'virtual | clear virtual users'
      ansible.builtin.file:
        path:  '{{ item }}'
        state: 'absent'
      failed_when: false
      loop:
        - '{{ vsftpd_default_virtual_users_file }}'
        - '{{ vsftpd_default_virtual_users_pam_file }}'
  when: vsftpd_virtual_users|length == 0
