---
# yamllint disable rule:line-length
###############################################################################
# Manager VSFTPd Virtual Users
###############################################################################
# Create virtual users.
#
# Args:
#   _vsftpd_virtual_users_file: str - absolute path to virtual_users.
#
# Reference:
# * https://wiki.archlinux.org/title/Very_Secure_FTP_Daemon
# * https://www.howtoforge.com/how-to-install-vsftpd-ftp-server-on-debian-11/
# * https://askubuntu.com/questions/575523/how-to-setup-virtual-users-for-vsftpd-with-access-to-a-specific-sub-directory
# * https://linuxconfig.org/how-to-setup-vsftpd-on-debian

- name: 'Virtual users | enable'
  when: vsftpd_service_virtual_users | length > 0
  block:
    - name: 'Virtual users | enable | clear virtual users'
      ansible.builtin.file:
        path: '{{ _vsftpd_virtual_users_file }}'
        state: 'absent'

    - name: 'Virtual users | enable | add virtual users'
      community.general.htpasswd:
        path: '{{ _vsftpd_virtual_users_file }}'
        name: '{{ item.user }}'
        password: '{{ item.pass }}'
        crypt_scheme: 'md5_crypt'
        owner: 'root'
        group: 'root'
        mode: '0640'
        state: 'present'
      loop: '{{ vsftpd_service_virtual_users }}'
      loop_control:
        label: '{{ item.user }}'

    - name: 'Virtual users | enable | add PAM vsftpd_virtual module'
      ansible.builtin.template:
        src: 'vsftpd_virtual.j2'
        dest: '{{ vsftpd_role_pam_virtual_users_module }}'
        owner: 'root'
        group: 'root'
        mode: '0644'

- name: 'Virtual users | disable'
  when: vsftpd_service_virtual_users | length == 0
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '{{ _vsftpd_virtual_users_file }}'
    - '{{ vsftpd_role_pam_virtual_users_module }}'
