---
# yamllint disable rule:line-length
###############################################################################
# Manage Virtual Users
###############################################################################
# Create virtual users.
#
# Reference:
# * https://wiki.archlinux.org/title/Very_Secure_FTP_Daemon
# * https://www.howtoforge.com/how-to-install-vsftpd-ftp-server-on-debian-11/
# * https://askubuntu.com/questions/575523/how-to-setup-virtual-users-for-vsftpd-with-access-to-a-specific-sub-directory
# * https://linuxconfig.org/how-to-setup-vsftpd-on-debian
# yamllint enable rule:line-length

- name: 'Virtual users | enable'
  when: vsftpd__srv._virtual_users | length > 0
  block:
    - name: '{{
          "Virtual users | filesystem | remove " ~ vsftpd___app._virtual_users
        }}'
      ansible.builtin.file:
        path: '{{ vsftpd___app._virtual_users }}'
        state: 'absent'

    - name: 'Virtual users | htpasswd | add virtual users'
      community.general.htpasswd:
        path: '{{ vsftpd___app._virtual_users }}'
        name: '{{ item.user }}'
        password: '{{ item.pass }}'
        crypt_scheme: 'md5_crypt'
        owner: 'root'
        group: 'root'
        mode: '0640'
        state: 'present'
      loop: '{{ vsftpd__srv._virtual_users }}'
      loop_control:
        label: '{{ item.user }}'

    - name:
        '{{ "Virtual users | filesystem | set " ~ vsftpd___app._virtual_pam }}'
      ansible.builtin.template:
        src: 'pam.d/vsftpd_virtual.j2'
        dest: '{{ vsftpd___app._virtual_pam }}'
        owner: 'root'
        group: 'root'
        mode: '0644'

- name: 'Virtual users | filesystem | remove virtual users'
  when: vsftpd__srv._virtual_users | length == 0
  ansible.builtin.file:
    path: '{{ item }}'
    state: 'absent'
  loop:
    - '{{ vsftpd___app._virtual_users }}'
    - '{{ vsftpd___app._virtual_pam }}'
