---
###############################################################################
# User Data
###############################################################################
# Default test with user data management enabled.
#
#
# Tests:
# * vsftpd_srv_user_data_manage_enable=true.
# * Test local user setup and login success.
# * standard service override works correctly (service running).
# * hardened service override works correctly (service running).
# * all remaining default options works correctly.

dependency:
  name: 'galaxy'
driver:
  name: 'podman'
provisioner:
  name: 'ansible'
  config_options:
    defaults:
      interpreter_python: 'auto_silent'
      callback_whitelist: 'profile_tasks, timer, yaml'
    ssh_connection:
      pipelining: false
  inventory:
    group_vars:
      all:
        vsftpd_srv_user_data_manage_enable: true
        vsftpd_cfg_write_enable: true
        vsftpd_cfg_chroot_local_user: true
        vsftpd_cfg_chroot_list_enable: true
        vsftpd_cfg_chroot_list:
          - 'test'
        vsftpd_cfg_ls_recurse_enable: true
    host_vars:
      vsftpd-debian-12-default-hardened:
        vsftpd_srv_harden_enable: true
platforms:
  - name: 'vsftpd-debian-12-user_data'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
  - name: 'vsftpd-debian-12-user_data-hardened'
    image: 'ghcr.io/hifis-net/debian-systemd:12'
    systemd: 'always'
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    pre_build_image: true
verifier:
  name: 'ansible'
lint: |
  set -e
  yamllint .
  ansible-lint .
scenario:
  test_sequence:
    # - 'dependency'
    # - 'cleanup'
    - 'destroy'
    - 'syntax'
    - 'create'
    - 'prepare'
    - 'converge'
    # - 'idempotence'  # service drop-ins always enforce.
    # - 'side_effect'
    - 'verify'
    # - 'cleanup'
    - 'destroy'
