---
###############################################################################
# vsftpd Handlers
###############################################################################

- name: 'restart vsftpd'
  ansible.builtin.systemd:
    name:    'vsftpd'
    state:   'restarted'
    enabled: true
