---
- name: 'Default | prepare'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | prepare | create local user test'
      ansible.builtin.user:
        name: 'test'
        create_home: true
        shell: /bin/bash
        password: '$y$j9T$hz4BpLr1xSfrN98ukZ.Sm.$K4k./xtB.bEmwL9X3fOhRII.q5uaMGvFDqL.AOY/dv.'  # yamllint disable-line rule:line-length
