---
# yamllint disable rule:line-length
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Default | verify | query vsftpd.conf'
      ansible.builtin.copy:
        src: 'files/vsftpd.conf'
        dest: '/etc/vsftpd.conf'
        owner: 'root'
        group: 'root'
        mode: '0644'
      check_mode: true
      diff: true
      register: _test_vsftpd_config

    - name: 'Default | verify | assert vsftpd.conf'
      ansible.builtin.assert:
        that:
          - not _test_vsftpd_config.changed
        fail_msg: >
          /etc/vsftpd.conf is not in expected format:
          {{ _test_vsftpd_config.diff }}.

    - name: 'Default | verify | assert vsftpd.service active'
      ansible.builtin.assert:
        that:
          - '"vsftpd.service" in ansible_facts.services'
          - 'ansible_facts["services"]["vsftpd.service"]["state"] == "running"'
        fail_msg: 'vsftpd.service should be enabled and running.'

    - name: 'Default | verify | query local user login success'
      ansible.builtin.command: 'wget --spider --tries=1 --user=test --password=test ftp://127.0.0.1'
      changed_when: false
      register: _test_vsftpd_test_login

    - name: 'Default | verify | assert local user login success'
      ansible.builtin.assert:
        that:
          - _test_vsftpd_test_login.rc == 0
        fail_msg: >
          test@127.0.0.1 should successfully login.
          ({{ _test_vsftpd_test_login.stderr }}).
