---
- name: 'Verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Verify | /etc/vsftpd.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'Verify | /etc/vsftpd.conf'
        test_src: 'files/vsftpd.conf'
        test_file: '/etc/vsftpd.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
        test_diff: true

    - name: 'Verify | query local user login success'
      ansible.builtin.command:
        argv:
          - 'wget'
          - '--spider'
          - '--tries=1'
          - '--user=test'
          - '--password=test'
          - 'ftp://127.0.0.1'
      changed_when: false
      register: _test_vsftpd_test_login

    - name: 'Verify | assert local user login success'
      ansible.builtin.assert:
        quiet: true
        that: _test_vsftpd_test_login.rc == 0
        fail_msg: |
          ╭───────────────────────────────────────────────────────────────────╮
          │                                                                   │
          │             test@127.0.0.1 should successfully login.             │
          │                                                                   │
          ├───────────────────────────────────────────────────────────────────╯
          │ {{ _test_vsftpd_test_login.stderr }}
