---
- name: 'VSFTPd.d | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'VSFTPd.d | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'VSFTPd.d | verify | assert vsftpd.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"vsftpd.service" in ansible_facts.services'
          - 'ansible_facts["services"]["vsftpd.service"]["state"] == "running"'
        fail_msg: '✘ vsftpd.service should be enabled and running.'

    - name: 'VSFTPd.d | verify | /etc/vsftpd.d'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'VSFTPd.d | verify | /etc/vsftpd.d/{{ item.file }}'
        test_src: 'files/{{ item.file }}'
        test_file: '/etc/vsftpd.d/{{ item.file }}'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '{{ item.mode }}'
        test_diff: true
      loop:
        - {file: 'banned_emails', mode: '0600'}
        - {file: 'banner_file', mode: '0644'}
        - {file: 'chroot_list', mode: '0600'}
        - {file: 'user_list', mode: '0600'}
        - {file: 'email_passwords', mode: '0600'}
      loop_control:
        label: '{{ item.file }}'

    - name: 'VSFTPd.d | verify | /etc/vsftpd.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'copy.yml'
      vars:
        test_name: 'VSFTPd.d | verify | /etc/vsftpd.conf'
        test_src: 'files/vsftpd.conf'
        test_file: '/etc/vsftpd.conf'
        test_owner: 'root'
        test_group: 'root'
        test_mode: '0644'
