---
- name: 'Default | verify'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Default | verify | gather service status'
      ansible.builtin.service_facts:

    - name: 'Default | verify | assert vsftpd.service active'
      ansible.builtin.assert:
        quiet: true
        that:
          - '"vsftpd.service" in ansible_facts.services'
          - 'ansible_facts["services"]["vsftpd.service"]["state"] == "running"'
        fail_msg: '✘ vsftpd.service should be enabled and running.'

    - name: 'Virtual users | verify | /etc/vsftpd.conf'
      ansible.builtin.include_role:
        name: 'r_pufky.lib.tests'
        tasks_from: 'lineinfile.yml'
      vars:
        test_name: 'Virtual users | verify | /etc/vsftpd.conf {{ item }}'
        test_file: '/etc/vsftpd.conf'
        test_line: '{{ item }}'
        test_state: 'present'
      loop:
        - 'guest_enable=YES'
        - 'pam_service_name=vsftpd_virtual'

    - name: 'Default | verify | query virtual user test login success'
      ansible.builtin.command:
        argv:
          - 'wget'
          - '--spider'
          - '--tries=1'
          - '--user=test'
          - '--password=test'
          - 'ftp://127.0.0.1'
      changed_when: false
      register: _test_vsftpd_test_login

    - name: 'Default | verify | assert virtual user test login success'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_vsftpd_test_login.rc == 0
        fail_msg: >
          ✘ test@127.0.0.1 should successfully login.
          ({{ _test_vsftpd_test_login.stderr }}).

    - name: 'Default | verify | query virtual user test2 login success'
      ansible.builtin.command:
        argv:
          - 'wget'
          - '--spider'
          - '--tries=1'
          - '--user=test2'
          - '--password=test2'
          - 'ftp://127.0.0.1'
      changed_when: false
      register: _test_vsftpd_test_login

    - name: 'Default | verify | assert virtual user test2 login success'
      ansible.builtin.assert:
        quiet: true
        that:
          - _test_vsftpd_test_login.rc == 0
        fail_msg: >
          ✘ test@127.0.0.1 should successfully login.
          ({{ _test_vsftpd_test_login.stderr }}).
